/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "chat.h"

void *
mensagem_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	printf("Msg: %s", *argp);

	return (void *) &result;
}
