/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "chat.h"

void
chat_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char * mensagem_1_arg;
	char msg[50];

#ifndef	DEBUG
	clnt = clnt_create (host, CHAT, CHAT_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	printf("Digite sua mensagem: ");
	gets(msg);
	
	mensagem_1_arg = msg;
		
	result_1 = mensagem_1(&mensagem_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char host[16];

	printf("Digite o ip: /n");
	gets(host);
	
	
	
	chat_1 (host);
exit (0);
}
