/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHAT_H_RPCGEN
#define _CHAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define CHAT 300000001
#define CHAT_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define mensagem 1
extern  void * mensagem_1(char **, CLIENT *);
extern  void * mensagem_1_svc(char **, struct svc_req *);
extern int chat_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define mensagem 1
extern  void * mensagem_1();
extern  void * mensagem_1_svc();
extern int chat_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHAT_H_RPCGEN */
